# NovaSDR Configuration — SDRplay RSP1A (curated)
# Device: SDRplay RSP1A via SoapySDR (rx_sdr -d driver=sdrplay)
# Capture format: s16 (16-bit signed IQ)
#
# Run example (LSB @ 7.1 MHz, 2 Msps):
#   rx_sdr -d driver=sdrplay -f 7100000 -s 2000000 - | ./build/spectrumserver --config config-rsp1a.toml
#
# Notes:
# - Start with 2 Msps and scale up only after confirming stability.
# - Keep waterfall zstd + FLAC audio unless you compiled additional codecs.
# - If CPU/memory is tight, reduce input.fft_size first, then input.sps.
# - On Raspberry Pi: keep accelerator="none" (GPU acceleration is not supported).

[server]
port = 9002
host = "0.0.0.0"
html_root = "frontend/dist/"
otherusers = 1
threads = 1

[websdr]
register_online = false
name = "NovaSDR (RSP1A)"
antenna = "HF Dipole"
grid_locator = "JO62"
hostname = ""
operator = "ChangeThis"
email = "example@test.com"
callsign_lookup_url = "https://www.qrz.com/db/"
chat_enabled = true

[limits]
audio = 100
waterfall = 200
events = 200

[input]
# Core parameters
sps = 2000000               # 2 Msps (increase only if resources allow)
frequency = 7100000         # Center frequency (Hz)
signal = "iq"               # RSP1A IQ via rx_sdr

# Performance and quality
fft_size = 131072           # Reduce if OOM or high CPU (e.g., 65536)
fft_threads = 1
brightness_offset = 0
audio_sps = 12000
waterfall_size = 1024
waterfall_compression = "zstd"
audio_compression = "flac"
accelerator = "none"        # Keep "none" on Raspberry Pi; "opencl"/"cuda"/"mkl" only if compiled and supported
smeter_offset = 0

[input.driver]
name = "stdin"
format = "s16"              # rx_sdr (driver=sdrplay) outputs s16 IQ

[input.defaults]
frequency = 7100000
modulation = "LSB"          # AM | SAM | FM | WBFM | USB | LSB
