# NovaSDR Configuration — RX888 MK2 (curated)
# Device: RX888 MK2 (direct/real sampling)
# Capture format: s16 (16-bit signed real)
#
# Run example (real sampling @ 6 Msps, LSB @ 3.645 MHz):
#   rx888_stream -s 6000000 | ./build/spectrumserver --config config-rx888mk2.toml
#
# Notes:
# - This profile uses moderate settings that start reliably on typical hosts.
# - RX888 MK2 can stream very high sample rates, but start at 6 Msps, then scale carefully.
# - Keep waterfall zstd + FLAC audio; these do not require extra codecs.
# - If CPU/memory is tight, reduce input.fft_size first, then input.sps.
# - On Raspberry Pi: keep accelerator="none" (GPU acceleration is not supported).

[server]
port = 9002
host = "0.0.0.0"
html_root = "frontend/dist/"
otherusers = 1
threads = 1

[websdr]
register_online = false
name = "NovaSDR (RX888 MK2)"
antenna = "Long wire"
grid_locator = "JO62"
hostname = ""
operator = "ChangeThis"
email = "example@test.com"
callsign_lookup_url = "https://www.qrz.com/db/"
chat_enabled = true

[limits]
audio = 100
waterfall = 200
events = 200

[input]
# Core parameters (REAL/direct sampling)
sps = 6000000                # 6 Msps to start; scale carefully
frequency = 3645000          # Center/base frequency (Hz) for real sampling
signal = "real"              # RX888 MK2 direct sampling (real)

# Performance and quality
fft_size = 131072            # Reduce if OOM or high CPU (e.g., 65536)
fft_threads = 1
brightness_offset = 0
audio_sps = 12000
waterfall_size = 1024
waterfall_compression = "zstd"
audio_compression = "flac"
accelerator = "none"         # Keep "none" on Raspberry Pi; use others only if compiled and supported
smeter_offset = 0

[input.driver]
name = "stdin"
format = "s16"               # rx888_stream outputs s16 (real)

[input.defaults]
frequency = 3645000
modulation = "LSB"           # AM | SAM | FM | WBFM | USB | LSB
