# NovaSDR Configuration — default template (curated)
# This file provides conservative defaults that start reliably on most hosts.
# Notes:
# - NovaSDR serves the built UI from server.html_root (no external web server required).
# - Required keys: input.sps, input.frequency, input.signal.
# - Start with the defaults below; raise sps/fft_size only after confirming stability.
# - On Raspberry Pi, keep accelerator="none" (GPU acceleration is not supported).

[server]
port = 9002
host = "0.0.0.0"
html_root = "frontend/dist/"
otherusers = 1
threads = 1

[websdr]
register_online = false
name = "ChangeThis"
antenna = "ChangeThis"
grid_locator = "ChangeThis"
hostname = ""
operator = "ChangeThis"
email = "example@test.com"
callsign_lookup_url = "https://www.qrz.com/db/"
chat_enabled = true

[limits]
audio = 100
waterfall = 200
events = 200

[input]
# Core stream settings
sps = 2048000
frequency = 100900000
signal = "iq"

# Performance and quality
fft_size = 131072
fft_threads = 1
brightness_offset = 0
audio_sps = 12000
waterfall_size = 1024
waterfall_compression = "zstd"
audio_compression = "flac"
accelerator = "none"
smeter_offset = 0

[input.driver]
name = "stdin"
format = "u8"

[input.defaults]
frequency = 100900000
modulation = "WBFM"

# Change the device profile:
# - RTL-SDR: format="u8", signal="iq", use rtl_sdr to pipe
# - HackRF: format="s8", signal="iq", use hackrf_transfer to pipe
# - Airspy HF+: format="s16", signal="iq", use airspy_rx to pipe
# - SDRplay RSP1A: format="s16", signal="iq", use rx_sdr -d driver=sdrplay
# - RX888 MK2 (real): format="s16", signal="real", use rx888_stream

# If you see "Out of memory" or high CPU:
# - reduce input.fft_size (e.g., 65536), then reduce input.sps
# Keep waterfall_compression="zstd" and audio_compression="flac" unless you compiled extra codecs.
