# PhantomSDR-Plus v2.0.0 Configuration Example - RTL-SDR
# This configuration is optimized for RTL-SDR dongles
# Usage: rtl_sdr -f 145000000 -s 2880000 - | ./spectrumserver --config config.toml

[server]
port=9002 # Server port for web interface
html_root="frontend/dist/" # Path to web interface files
otherusers=1 # Show other users' listening frequencies (1=enabled, 0=disabled)
threads=1 # Number of processing threads (adjust based on CPU cores)

[websdr]
register_online=false # Register WebSDR on https://sdr-list.xyz (true=public, false=private)
name="My RTL-SDR WebSDR" # Station name displayed on sdr-list.xyz and web interface
antenna="Discone Antenna" # Antenna description shown to users
grid_locator="JO20KV" # 4 or 6 character grid locator for distance calculations
hostname="" # Domain name for public access (leave empty for local use)
operator="Your Callsign" # Operator name/callsign displayed in station info
email="your.email@example.com" # Contact email for station information
callsign_lookup_url="https://www.qrz.com/db/" # URL for callsign lookups in server info panel
chat_enabled=true # Enable/disable chat functionality (new in v2.0.0)

[limits]
# Connection limits to prevent server overload
audio=1000 # Maximum audio connections
waterfall=1000 # Maximum waterfall connections
events=1000 # Maximum event connections

[input]
# RTL-SDR optimized settings
sps=2880000 # Input sample rate (RTL-SDR typical: 2.88MHz)
fft_size=131072 # FFT bins for spectral analysis (power of 2: 32768, 65536, 131072, 262144)
brightness_offset=0 # Waterfall brightness adjustment (-50 to +50, negative = darker)
frequency=145000000 # Center frequency in Hz (145MHz for 2m amateur band)
signal="iq" # Signal type: "iq" for complex samples, "real" for real samples
accelerator="none" # GPU acceleration: "none", "cuda", "opencl" (requires OpenCL/CUDA)
audio_sps=12000 # Audio sample rate for demodulated output (12kHz typical)
audio_compression="flac" # Audio compression: "flac" (lossless only)
waterfall_size=2048 # Waterfall display width in pixels
waterfall_compression="zstd" # Waterfall compression: "zstd" only
smeter_offset=0 # S-meter calibration offset in dB

[input.driver]
name="stdin" # Input driver: "stdin" for piped data
format="u8" # Sample format for RTL-SDR: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
# Default settings when users first connect
frequency=145500000 # Default frequency to display (145.5MHz)
modulation="FM" # Default modulation mode: AM, FM, USB, LSB, CW, WBFM
