# PhantomSDR-Plus v2.0.0 Configuration Example - Airspy HF+
# This configuration is optimized for Airspy HF+ Discovery
# Usage: airspy_rx -r - -f 456000 -s 912000 | ./spectrumserver --config config.toml

[server]
port=81 # Server port for web interface (different from other configs)
html_root="frontend/dist/" # Path to web interface files
otherusers=1 # Show other users' listening frequencies (1=enabled, 0=disabled)
threads=2 # Number of processing threads (Airspy HF+ benefits from multiple threads)

[websdr]
register_online=false # Register WebSDR on https://sdr-list.xyz (true=public, false=private)
name="My Airspy HF+ WebSDR" # Station name displayed on sdr-list.xyz and web interface
antenna="HF Magnetic Loop" # Antenna description shown to users
grid_locator="JO20KV" # 4 or 6 character grid locator for distance calculations
hostname="" # Domain name for public access (leave empty for local use)
operator="Your Callsign" # Operator name/callsign displayed in station info
email="your.email@example.com" # Contact email for station information
callsign_lookup_url="https://www.qrz.com/db/" # URL for callsign lookups in server info panel
chat_enabled=true # Enable/disable chat functionality (new in v2.0.0)

[limits]
# Connection limits to prevent server overload
audio=1000 # Maximum audio connections
waterfall=1000 # Maximum waterfall connections
events=1000 # Maximum event connections

[input]
# Airspy HF+ optimized settings - HF/VHF with excellent dynamic range
sps=912000 # Input sample rate (Airspy HF+: 192k, 256k, 384k, 456k, 768k, 912k)
fft_size=131072 # FFT bins for spectral analysis (good resolution for HF)
fft_threads=2 # Number of FFT processing threads
brightness_offset=-6 # Waterfall brightness adjustment (Airspy HF+ typically darker)
frequency=456000 # Center frequency in Hz (456kHz for MW/LW coverage)
signal="iq" # Signal type: "iq" for complex samples (Airspy HF+ provides IQ)
accelerator="opencl" # GPU acceleration recommended for better performance
audio_sps=44100 # Audio sample rate for demodulated output (CD quality)
audio_compression="flac" # Audio compression: "flac" (lossless only)
waterfall_size=2048 # Waterfall display width in pixels
waterfall_compression="zstd" # Waterfall compression: "zstd" only
smeter_offset=-12 # S-meter calibration offset in dB (Airspy HF+ specific)

[input.driver]
name="stdin" # Input driver: "stdin" for piped data from airspy_rx
format="s16" # Sample format for Airspy HF+: s16 (16-bit signed integers)

[input.defaults]
# Default settings when users first connect
frequency=648000 # Default frequency to display (648kHz - MW band)
modulation="AM" # Default modulation mode: AM for MW broadcast band
