# NovaSDR Configuration — Airspy HF+ (curated)
# Device: Airspy HF+ via airspy_rx
# Capture format: s16 (16-bit signed IQ)
#
# Run example (AM @ 648 kHz, 912 ksps):
#   airspy_rx -r - -f 648000 -s 912000 | ./build/spectrumserver --config config-airspyhf.toml
#
# Notes:
# - Airspy HF+ offers several supported rates (e.g., 192k, 256k, 384k, 456k, 768k, 912k). 912k is a solid default.
# - Keep waterfall zstd + FLAC audio; these do not require extra codecs.
# - Avoid "opus" and "av1" unless NovaSDR was compiled with those codecs.
# - If CPU/memory is tight, reduce input.fft_size first, then input.sps.

[server]
port = 9002
host = "0.0.0.0"
html_root = "frontend/dist/"
otherusers = 1
threads = 1

[websdr]
register_online = false
name = "NovaSDR (Airspy HF+)"
antenna = "HF Magnetic Loop"
grid_locator = "JO62"
hostname = ""
operator = "ChangeThis"
email = "example@test.com"
callsign_lookup_url = "https://www.qrz.com/db/"
chat_enabled = true

[limits]
audio = 100
waterfall = 200
events = 200

[input]
# Core parameters
sps = 912000                 # 912 ksps (good default for HF+)
frequency = 648000           # Center frequency (Hz)
signal = "iq"                # Airspy HF+ outputs IQ

# Performance and quality
fft_size = 131072            # Reduce if OOM or high CPU (e.g., 65536)
fft_threads = 1
brightness_offset = 0        # Adjust (-6 .. +6) if WF is too dark/bright
audio_sps = 44100
waterfall_size = 1024
waterfall_compression = "zstd"
audio_compression = "flac"
accelerator = "none"         # "none" | "opencl" | "cuda" | "mkl" (only if compiled)
smeter_offset = 0

[input.driver]
name = "stdin"
format = "s16"               # airspy_rx outputs s16 IQ

[input.defaults]
frequency = 648000
modulation = "AM"            # AM | SAM | FM | WBFM | USB | LSB
