# NovaSDR Configuration — HackRF One (curated)
# Device: HackRF One via hackrf_transfer
# Capture format: s8 (8-bit signed IQ)
#
# Run example (WBFM @ 100.9 MHz, 8 Msps):
#   hackrf_transfer -r - -f 100900000 -s 8000000 | ./build/spectrumserver --config config.example.hackrf.toml
#
# Notes:
# - 8 Msps is demanding but practical on many systems; start here and scale down to 4–6 Msps if CPU is high.
# - Keep waterfall zstd + FLAC audio; these do not require extra codecs.
# - Avoid "opus" and "av1" unless NovaSDR was compiled with those codecs.
# - If CPU/memory is tight, reduce input.fft_size, then input.sps.

[server]
port = 9002
host = "0.0.0.0"
html_root = "frontend/dist/"
otherusers = 1
threads = 1

[websdr]
register_online = false
name = "NovaSDR (HackRF)"
antenna = "Wideband"
grid_locator = "JO62"
hostname = ""
operator = "ChangeThis"
email = "example@test.com"
callsign_lookup_url = "https://www.qrz.com/db/"
chat_enabled = true

[limits]
# Multi-user caps; adjust to your host capacity
audio = 100
waterfall = 200
events = 200

[input]
# Core parameters
sps = 8000000                 # 8 Msps (reduce to 4000000–6000000 if CPU is high)
frequency = 100900000         # Center frequency (Hz)
signal = "iq"                 # HackRF outputs IQ

# Performance and quality
fft_size = 131072             # Increase for more resolution if resources allow
fft_threads = 1
brightness_offset = 0
audio_sps = 12000
waterfall_size = 1024
waterfall_compression = "zstd"  # Leave as "zstd" unless AV1 compiled
audio_compression = "flac"      # Leave as "flac" unless Opus compiled
accelerator = "none"            # "none" | "opencl" | "cuda" | "mkl" (only if compiled)
smeter_offset = 0

[input.driver]
name = "stdin"
format = "s8"                 # hackrf_transfer outputs s8 IQ

[input.defaults]
frequency = 100900000
modulation = "WBFM"           # AM | SAM | FM | WBFM | USB | LSB
